version: '3.8'

services:
  # Node.js Backend Service
  backend:
    build: .
    container_name: node-backend
    ports:
      - "3001:3001"  # Expose port 3001 to match your frontend request
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows using host.docker.internal to reach the host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
