version: '3.8'

services:
  # Node.js Backend Service with HTTPS
  backend:
    build: .
    container_name: node-backend
    ports:
      - "3001:3001"  # HTTP port
      - "3443:3001"  # HTTPS port
      - "80:3001"    # Fallback HTTP port
      - "443:3001"   # Fallback HTTPS port
    volumes:
      - ./src:/app/src
      - ./ssl:/app/ssl:ro  # Mount SSL certificates as read-only
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
