version: '3.8'

services:
  # Node.js Backend Service with HTTPS
  backend:
    build: .
    container_name: node-backend
    ports:
      - "3001:3001"  # HTTP port (for health checks)
      - "3443:3001"  # HTTPS port
    volumes:
      - ./src:/app/src
      - ./ssl:/app/ssl:ro  # Mount SSL certificates as read-only
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
